#!/usr/bin/env python3
"""
Sync the local Marp Player tree to github.com/techbuzzz/marp-play using the
GitHub Git Database API (trees + commits) — faster and atomic compared to the
Contents API.

It reads GITHUB_TOKEN from nextjs_space/.env and expects the working tree at
/home/ubuntu/marp_player/ (override with --root).

Usage:
    python3 scripts/sync_to_github.py -m "chore: add README and docs"
    python3 scripts/sync_to_github.py --dry-run
"""
from __future__ import annotations

import argparse
import base64
import fnmatch
import os
import sys
import time
from pathlib import Path
from typing import Iterable

import requests

OWNER = "techbuzzz"
REPO = "marp-play"
BRANCH = "main"
API = f"https://api.github.com/repos/{OWNER}/{REPO}"

# Any path containing one of these directory names at any depth is excluded.
EXCLUDE_DIR_NAMES = {
    ".git",
    "node_modules",
    ".next",
    ".build",
    ".deploy",
    ".logs",
    "dist",
    "out",
    "target",
    "cache",  # only under .yarn/
}

# Exact filenames to skip.
EXCLUDE_FILE_NAMES = {
    ".abacus.donotdelete",
    ".env",
    ".env.local",
    "install-state.gz",
    "build-state.yml",
    "yarn.lock",  # symlink on this box, regenerated by CI anyway
}

# Glob patterns (fnmatch-style, against the basename or full rel path).
EXCLUDE_PATTERNS = [
    "*.tsbuildinfo",
    "*.nfs*",
    "*.log",
]

MAX_FILE_BYTES = 25 * 1024 * 1024  # GitHub blob upload limit is 100MB; keep it sane.


def load_env(root: Path) -> None:
    env_path = root / "nextjs_space" / ".env"
    if not env_path.exists():
        return
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        v = v.strip().strip('"').strip("'")
        os.environ.setdefault(k.strip(), v)


def is_excluded(rel: str) -> bool:
    parts = rel.split("/")
    # Directory-name matches at any depth
    for seg in parts[:-1]:
        if seg in EXCLUDE_DIR_NAMES:
            return True
    # Exact filename match
    if parts[-1] in EXCLUDE_FILE_NAMES:
        return True
    # Pattern matches against basename
    for pat in EXCLUDE_PATTERNS:
        if fnmatch.fnmatch(parts[-1], pat):
            return True
    return False


def iter_files(root: Path) -> Iterable[Path]:
    for p in root.rglob("*"):
        if p.is_symlink():
            continue
        if not p.is_file():
            continue
        rel = p.relative_to(root).as_posix()
        if is_excluded(rel):
            continue
        try:
            size = p.stat().st_size
        except OSError:
            continue
        if size > MAX_FILE_BYTES:
            print(f"[skip >25MB] {rel} ({size} bytes)", file=sys.stderr)
            continue
        yield p


class GH:
    def __init__(self, token: str):
        self.s = requests.Session()
        self.s.headers.update({
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        })

    def _req(self, method: str, url: str, **kw):
        for attempt in range(4):
            r = self.s.request(method, url, timeout=60, **kw)
            if r.status_code in (502, 503, 504) and attempt < 3:
                time.sleep(2 ** attempt)
                continue
            if not r.ok:
                raise RuntimeError(f"{method} {url} -> {r.status_code}: {r.text[:400]}")
            return r
        raise RuntimeError(f"{method} {url} kept failing")

    def get(self, path: str):
        return self._req("GET", API + path).json()

    def post(self, path: str, payload: dict):
        return self._req("POST", API + path, json=payload).json()

    def patch(self, path: str, payload: dict):
        return self._req("PATCH", API + path, json=payload).json()

    def create_blob(self, content_bytes: bytes) -> str:
        resp = self.post(
            "/git/blobs",
            {
                "content": base64.b64encode(content_bytes).decode("ascii"),
                "encoding": "base64",
            },
        )
        return resp["sha"]

    def create_tree(self, entries: list[dict]) -> str:
        # Split into chunks of 500 to stay under payload limits.
        base_tree = None
        for i in range(0, len(entries), 500):
            chunk = entries[i : i + 500]
            payload = {"tree": chunk}
            if base_tree:
                payload["base_tree"] = base_tree
            resp = self.post("/git/trees", payload)
            base_tree = resp["sha"]
        assert base_tree is not None
        return base_tree

    def create_commit(self, message: str, tree_sha: str, parents: list[str]) -> str:
        resp = self.post(
            "/git/commits",
            {
                "message": message,
                "tree": tree_sha,
                "parents": parents,
            },
        )
        return resp["sha"]

    def update_ref(self, branch: str, sha: str, force: bool = False) -> dict:
        return self.patch(
            f"/git/refs/heads/{branch}",
            {"sha": sha, "force": force},
        )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="/home/ubuntu/marp_player")
    ap.add_argument("-m", "--message", default="chore: sync from Abacus AI")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--force", action="store_true", help="Force-update the ref")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    if not root.exists():
        print(f"root does not exist: {root}", file=sys.stderr)
        return 2

    load_env(root)
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("GITHUB_TOKEN not set and not found in nextjs_space/.env", file=sys.stderr)
        return 2

    files = sorted(iter_files(root))
    total_bytes = sum(p.stat().st_size for p in files)
    print(f"Collected {len(files)} files, {total_bytes/1024/1024:.1f} MiB total.")
    if args.dry_run:
        for p in files[:40]:
            print("  ", p.relative_to(root))
        if len(files) > 40:
            print(f"  ... and {len(files) - 40} more")
        return 0

    gh = GH(token)

    head = gh.get(f"/git/refs/heads/{BRANCH}")
    parent_sha = head["object"]["sha"]
    print(f"HEAD of {BRANCH}: {parent_sha}")

    tree_entries: list[dict] = []
    for i, p in enumerate(files, 1):
        rel = p.relative_to(root).as_posix()
        data = p.read_bytes()
        mode = "100755" if os.access(p, os.X_OK) else "100644"
        blob_sha = gh.create_blob(data)
        tree_entries.append({"path": rel, "mode": mode, "type": "blob", "sha": blob_sha})
        if i % 25 == 0 or i == len(files):
            print(f"  [{i}/{len(files)}] uploaded")

    # We want the commit tree to be EXACTLY the set of local files (not a merge
    # with the previous tree) so that deleted files are actually removed on
    # GitHub. Do not pass base_tree.
    print("Creating tree...")
    tree_sha = gh.create_tree(tree_entries)
    print("  tree:", tree_sha)

    commit_sha = gh.create_commit(args.message, tree_sha, [parent_sha])
    print("  commit:", commit_sha)

    updated = gh.update_ref(BRANCH, commit_sha, force=args.force)
    print("  ref:", updated["object"]["sha"])
    print(f"✅ Pushed to https://github.com/{OWNER}/{REPO}/commit/{commit_sha}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
